basePath: /
host: localhost:8080
info:
  contact: {}
  description: API Server for URL-shortener Application
  title: URL-shortener backend
  version: "1.0"
paths:
  /a:
    post:
      consumes:
      - application/json
      description: add url
      operationId: add-url
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: AddUrl
      tags:
      - url
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
